seed: 42
device: "cuda"  # or "cpu" if GPU is not available
data:
  train_images_dir: "data/train/images"
  train_masks_dir: "data/train/masks"
  val_images_dir: "data/val/images"
  val_masks_dir: "data/val/masks"
  image_size: 256
  batch_size: 8
  num_workers: 4
model:
  in_channels: 1
  out_channels: 1
loss:
  type: "bce-dice"
  bce_weight: 0.5
train:
  num_epochs: 50
  learning_rate: 0.0001
  checkpoint_dir: "runs"